### ISSUE TITLE
Add Answer on UDP request 

### ISSUE THREAD

**Issue by NPuhlmann** [NPuhlmann/LEDChanger_Server#2]
I did some changes to the app to do an autodiscover of the server IP by UDP Broadcast. The App now runs a method called "discoverServer", which sends a broadcast to '255.255.255.255:1234' .
The Text of the message is 

> DISCOVER_MSG 

I want the Server to listen to this broadcast and answer with message: 

> ANSWER_MSG

when getting this message the app extracts the IP of the server and proceed as usual. 
Could you please set this up ASAP?

Greetings, 
Nico

**Comment by D4ywa1k3r** [comment]
UDP Answer was implemented and located in the new tcp branch
